### ISSUE TITLE
Feature Request : toast banner or pop-up

### ISSUE THREAD

**Issue by CySxL** [Yot360/DebLoader#1]
I think having a toast banner or pop-up window to notify user that the download task is done will be nice !!!

**Comment by Yot360** [comment]
That's a great idea! I will try to add that soon, thanks

**Comment by Yot360** [comment]
Added it, simply update the app from the repo!

https://user-images.githubusercontent.com/65982248/175123132-4291c3d4-4307-4870-afb1-ac262c60eda0.mp4

**Comment by CySxL** [comment]
> Added it, simply update the app from the repo!
> 
> 
> 
> https://user-images.githubusercontent.com/65982248/175123132-4291c3d4-4307-4870-afb1-ac262c60eda0.mp4
> 
> 
> 
>  

Thanks a lot !! u r awesome !!
